


/*INFO CIUDAD*/
INSERT INTO CIUDAD VALUES (1,'barcelona');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (2'victoria Gasteiz');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (3'bilbao');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (4'badajoz');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (5'eibar');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (6'valencia');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (7'san sebastien');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (8'sevilla');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (9'melilla');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (10'ceuta');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (11'jaen');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (12'Madrid');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (13'benidum');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (14'cadiz');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (15'granada');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (16'levante');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (17'villarial');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (18'sevilla betis');
INSERT INTO CIUDAD (CODIGOCIUDAD,NOMBRE) VALUES (19'espagnol');
/*INFO EMPLEADO*/
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,CODIGOPOSTAL,E-MAIL'),
VALUES('782463958r','rsa maria fenandez','254067940','espagnol',
'v/tomas','15874','yh1fd@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,CODIGOPOSTAL,E-MAIL'),
VALUES('782463958u','rosa aria fernande','254318940','sevilla betis',
'c/juan','21458','yhg0fd@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,CODIGOCIUDAD,E-MAIL'),
VALUES('782463058h','jota mario fernandek','554368940','levante',
'v/paul','00145','yhgfd0@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,CODIGOCIUDAD,E-MAIL'),
VALUES('78j463958g',' juanmari fernandez','204308940','granada',
'd/Madri','10204','yhlkgfd@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,CODIGOPOSTAL,E-MAIL'),
VALUES('782463058d',' jose fernandiez','254302940','villarial',
'c/josemaria','54215','yhgf21d@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,CODIGOPOSTAL,E-MAIL'),
VALUES('782463950b','maria alejandra fernandez','211368940','cadiz',
'v/Madrios','65485','y10hgfd@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,CODIGOPOSTAL,E-MAIL'),
VALUES('786663958g','alejandra maria fernandez','254300940','benidum',
'c/jadrid','75841','yhgfjgdd@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,CODIGOPOSTAL,E-MAIL'),
VALUES('782463958g','rosa maria fernandez','254368940','Madrid',
'v/Madrid','yhgfd@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,CODIGOPOSTAL,E-MAIL'),
VALUES('782463958g','rosa maria fernandez','254368940','melilla',
'v/Madrid','yhgfd@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,E-MAIL'),
VALUES('905478152m','taria Hernández','644473874','victoria Gasteiz',
'v/fernandez Garcia','tyhnd@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,E-MAIL'),
VALUES('945478152m','taria Hernándo','644473074','bilbao',
'v/fernandez Garcia','tyhnd@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,E-MAIL'),
VALUES('782463958t','rosaria maria fernando','254368941','badajoz',
'c/Madrid','ohgfd@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,E-MAIL'),
VALUES('732463958g','ros maria jernandez','154368940','eibar',
'v/diego plaza','yhjhgfd@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,E-MAIL'),
VALUES('702463958g','rosi maria fernando','954368940','san sebastien',
'c/dato','zzyhgfd@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,E-MAIL'),
VALUES('742463958g','franc fernandez','284368940','valencia',
'v/Madrid','yiihgfd@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,E-MAIL'),
VALUES('782363958g','pau Garcia fernandez','054368940','sevilla',
'v/fernandez','yyyhgfd@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,E-MAIL'),
VALUES('782433958g','rosa maria fernandez','254368940','ceuta',
'v/santiago','azyhgfd@gmail.com');
INSERT INTO EMPLEADO('DNI,NOMBRE,TELEFONO,CIUDAD,DIRECCION,CP,E-MAIL'),
VALUES('782463958g','rosa maria fernandez','254368940','jaen',
'v/Madrid','08965','yhgfd@gmail.com');
/* INFO TABLAEMPLEADO */
TABLA EMPLEADO(
  DNI INT('12'),
  NOMBRE INT('44'),
  TELEFONO INT('12'),
  CIUDAD VARCHAR('15'),
  DIRECCION VARCHAR('23'),
  E-MAIL NULL('36'),
);
/*INSERTE CLIENTES*/
INSERT INTO CLIENTES('DNI CLIENTES','NOMBRE,TELEFONO,PAIS,CIUDAD,DIRECCION,E-MAIL'),
VALUES('985478152h','maria Hernández','644473870','Francia',
'c/fernando Garcia','ghnd@gmail.com');
INSERT INTO CLIENTES('DNI CLIENTES','NOMBRE,TELEFONO,PAIS,CIUDAD,DIRECCION,E-MAIL'),
VALUES('985478155h','maris Hernández','644473871','englattera',
  'liverpool','c/fernandez Garcia','ghvd@gmail.com');
INSERT INTO CLIENTES('DNI CLIENTES','NOMBRE,TELEFONO,PAIS,CIUDAD,DIRECCION,E-MAIL'),
VALUES('985478154h','maria fernández','644473878','paise bajo','amsterdam',
,'c/hernando Garcia','ghud@gmail.com');
INSERT INTO CLIENTES('DNI CLIENTES','NOMBRE,TELEFONO,PAIS,CIUDAD,DIRECCION,E-MAIL'),
VALUES('985478052v','juan gonzalez','644473800','alemania','berlin',
,'a/fernandez Garcia','dohnd@gmail.com');
INSERT INTO CLIENTES('DNI CLIENTES','NOMBRE,TELEFONO,PAIS,CIUDAD,DIRECCION,E-MAIL'),
VALUES('995478152y','pablo Hernández','644173870','italia','milan',
,'c/fernando alonso','ghuoih@gmail.com');
/*CREER CODIGOCLIENTES*/
CREATE TABLA CLIENTES(
  DNI TEXT('12'),
  NOMBRE TEXT(36),
  TELEFONO int('12'),
  PAIS NULL('10'),
  CIUDAD NULL('1'),
  DIRECCION int('25'),
  E-MAIL int('20'),
);
/*CREER CODIGOAUTOMOBILE*/
INSERT INTO AUTOMOBILE('marcas','modelo','matricula','precio,'),
VALUES('Mercedes benz','MG220','L25W62','9500);
INSERT INTO AUTOMOBILE('marcas,modelo,matricula,precio,'),
VALUES('Mercedes Benz,GM240,S254GW,92000,');
INSERT INTO AUTOMOBILE('marcas,modelo,matricula,precio,'),
VALUES('Mercedes ,GT240,S254TW,82000,');
INSERT INTO AUTOMOBILE('marcas,modelo,matricula,precio,'),
VALUES('TOYATA,TM240,D254GW,92000,');
INSERT INTO AUTOMOBILE('marcas,modelo,matricula,precio,'),
VALUES('TOYATA YARIS,GM244,S254GK,91000,');
INSERT INTO AUTOMOBILE('marcas,modelo,matricula,precio,'),
VALUES('PEUGEOT,GM240T,S254GF,42000,');
INSERT INTO AUTOMOBILE('marcas,modelo,matricula,precio,'),
VALUES('HUMMER,GM242T,I254GW,99000,');
INSERT INTO AUTOMOBILE('marcas,modelo,matricula,precio,'),
VALUES('HAMBORGINI,GTML240,254GWT,99500,');
INSERT INTO AUTOMOBILE('marcas,modelo,matricula,precio,'),
VALUES('AUDI CUPE,TGM240,SI254GW,78000,');
INSERT INTO AUTOMOBILE('marcas,modelo,matricula,precio,'),
VALUES('AUDI,SM240,S154GW,95000');
INSERT INTO AUTOMOBILE('marcas,modelo,matricula,precio,'),
VALUES('PORCHE,GMD240,T254GW,99900');
INSERT INTO AUTOMOBILE('marcas,modelo,matricula,precio,'),
VALUES('FERRARRI CUPE,SGM240,S254GW,93500');
INSERT INTO AUTOMOBILE('marcas,modelo,matricula,precio,'),
VALUES('ferrarri,PGM24,S254G,62000,');
 CREAR DATABASE VENTE_COCHE;
/*INSERTAR TABLAAUTOMOBILE*/
CREAR TABLA AUTOMOBILE(
  DESCRIPCION VARCHAR('60')NOT NULL,
  DESCRIPCION VARCHAR('60')NOT NULL,
  DESCRIPCION VARCHAR('60')NOT NULL,
  DESCRIPCION VARCHAR('60')NOT NULL,
  DESCRIPCION VARCHAR('60'),
  CODIGOAUTOMOBILE
  PRYMARY KEY('marcas'),
  CONSTRAINT CANDIDADAUTOMOBILE FOREIGN KEY(marcas)REFERENCES AUTOMOBILE
);
